name: capcut_video_editor
description: Editor FS - A sleek, modern video editing app built with Flutter.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.5.1
  flutter_riverpod: ^2.5.1
  file_picker: ^8.1.2
  video_player: ^2.9.2
  video_player_win: ^3.2.2
  audioplayers: 6.1.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  shaders:
    - assets/shaders/transitions/crossfade.frag
    - assets/shaders/transitions/fade_black.frag
    - assets/shaders/transitions/fade_white.frag
    - assets/shaders/transitions/wipe_left.frag
    - assets/shaders/transitions/wipe_right.frag
    - assets/shaders/transitions/wipe_up.frag
    - assets/shaders/transitions/wipe_down.frag
    - assets/shaders/transitions/slide_left.frag
    - assets/shaders/transitions/slide_right.frag
    - assets/shaders/transitions/slide_up.frag
    - assets/shaders/transitions/slide_down.frag
    - assets/shaders/transitions/zoom_in.frag
    - assets/shaders/transitions/zoom_out.frag
    - assets/shaders/transitions/circle.frag
    - assets/shaders/transitions/radial.frag
    - assets/shaders/transitions/blur.frag
    - assets/shaders/transitions/pixelate.frag
